{{- if and (not .Values.slack.existingSecretName) .Values.slack.webhookUrl -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "deploy-guard.fullname" . }}-slack
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy-guard.labels" . | nindent 4 }}
type: Opaque
stringData:
  SLACK_WEBHOOK: {{ .Values.slack.webhookUrl | quote }}
{{- end }}
