{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deploy-guard.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "deploy-guard.labels" . | nindent 4 }}
{{- end }}
